### ISSUE TITLE
[1:00] Brandyn Bishop

### ISSUE THREAD

**Issue by Renandal** [laboon/cs0401#100]
Hi, Professor Laboon!

**Comment by laboon** [comment]
Howdy!

**Comment by laboon** [comment]
I actually have a "Brandyn Bishop" in my 3:00 class, I assume that's you?

**Comment by Renandal** [comment]
Yes that would be me. Suppose I didn't notice the error there  

```
 On Tuesday, September 15, 2015 5:08 PM, Bill Laboon <notifications@github.com> wrote:
```

 I actually have a "Brandyn Bishop" in my 3:00 class, I assume that's you?—
