### ISSUE TITLE
Question about the assignment 2

### ISSUE THREAD

**Issue by pavel121** [laboon/cs0401#114]
In the assignment 2, there is one bonus option:
       "Allow the user the option of paying by credit card.  This may
       involve inputting the card number (or some other simulated
       activity) and checking it against a list of invalid credit
       cards in a file.  Only a valid credit card may be used."
What does it mean "a list of invalid credit cards in a file"? Just open a TXT file and write some possible credit card numbers, and then make the program to read this file, and compare entered credit card to the credit cards from the list? If so, should I add this TXT file with the program?

Thank you, 
Pavel

**Comment by laboon** [comment]
Yes, exactly. For partial credit these can be stored in the Java program
itself.

**Comment by pavel121** [comment]
Thank you for the answer.
