### ISSUE TITLE
Issue with the grading rubric of assignment 2 (Pizza Cash Register)

### ISSUE THREAD

**Issue by lhiginbotham** [laboon/cs0401#115]
The grading rubric says the program must be able to 
"Allows users to buy pizza by slice and by entire pie"
but the instructions for the assignment do not mention a price per pizza slice or how many slices make up a pizza.

**Comment by laboon** [comment]
Whoops, error on the grading rubric.  Just fixed it.

+2 bonus points on this assignment for you for catching it.

**Comment by laboon** [comment]
On the submission sheet comments, please note -
"+2 bonus points from Issue #115"

**Comment by lhiginbotham** [comment]
Wow, thanks!
