### ISSUE TITLE
[1:00 / 3:00] Stephen Sortman

### ISSUE THREAD

**Issue by sds84** [laboon/cs0401#118]
Hi Professor Laboon

**Comment by laboon** [comment]
Stephen - let me know once you know if you're in the 1:00 or 3:00 section so I can add you to the roster. Thanks!

**Comment by sds84** [comment]
Prof Laboon,

I have to get a permission number from Angela and she has been out of the office but returns tomorrow so I will be getting it off of her. I will be attending your 3:00 class and the lab is Monday from 11-1250.

Steve
