### ISSUE TITLE
"Zip" instruction

### ISSUE THREAD

**Issue by j-w-yun** [laboon/cs0401#123]
Self-explanatory reply from professor Laboon regarding the instructions for assignment 3.

"Hi Jaewan -
   Thanks for the email.  The "zip" instruction should not be there - I
have fixed it to just say "submit all the Java files" which I assuma
makes more sense. For finding that mistake, you get an additional +2
extra credit points _if_ you submit it as an issue on the cs0401
repository. [...]"

**Comment by laboon** [comment]
Points were given, closing issue
