### ISSUE TITLE
[1:00, James Hahn] Initial betting money unclear

### ISSUE THREAD

**Issue by kingsman142** [laboon/cs0401#124]
In the assignment instructions, it is unclear whether the game should give a new player a pre-defined amount of betting money or if they should be able to add an initial amount to their account.  Bill explains how it should be:

Bill Laboon: "If they're new, they should be allowed to input how much money they want
to initially bet.  This doesn't seem to be stated clearly in the
assignment, although it is in the sample output:

Welcome New Player!
Please enter your information below:
Last Name: Inglenook
Initial money: 100

If you file an issue on the CS0401 class repo stating that this isn't
clear, you'll get two extra credit points for noting a problem..."

**Comment by laboon** [comment]
Points were given, closing issue
