### ISSUE TITLE
[1:00, James Hahn] Exam 1 Review Guide

### ISSUE THREAD

**Issue by kingsman142** [laboon/cs0401#126]
In the Exam 1 review guide, there is a link to the debug.ptt slides.  However, this link leads to a 404 Page Cannot Be Found error, not allowing students to study debugging.

**Comment by GideonShils** [comment]
In case anyone else hasn't found the debug.ppt, it can be found under the java-tips section. Here is a direct link as well: http://people.cs.pitt.edu/~ramirez/cs401/debug.pptx

**Comment by laboon** [comment]
Thanks - I will put this up now.
