### ISSUE TITLE
Lab07 Martin Garden issue

### ISSUE THREAD

**Issue by coltonb** [laboon/cs0401#127]
In the lab, the directions state "Martin is so pessimistic that he will only increase the size of his garden by 2 even if there are more than 2 rutabagas that season!" The sample output directly contradicts this, in that on the 10th season there are 4 rutabagas that Martin resizes his garden twice for.

**Comment by laboon** [comment]
Right, he resized it twice.  So he says: "Ugh, I don't have any more room for 4 rutabagas" and he resizes it by 2.  Then it turns out he has 2 rutabagas that don't fit, so he has to resize it _again_ to fit those.  The garden will still eventually fit all of the rutabagas.

**Comment by laboon** [comment]
I think this issue was resolved.  let me know if not by re-opening it.
