### ISSUE TITLE
Two Week 13s in the Syllabus

### ISSUE THREAD

**Issue by kingsman142** [laboon/cs0401#128]
In the syllabus.md file, there are two week 13s.  The week of 23 Nov should be Week 13 and then the week of 30 Nov should be Week 14, which would push the final week of 7 Dec to Week 15.

**Comment by laboon** [comment]
Fixed in commit 34dbfade5f967b2bed062d7386b39938f47902d7, thanks!

If you email me your (actual, not GitHub) name you will get +2 bonus points on your latest assignment for finding this.

**Comment by laboon** [comment]
Added two bonus points for this!  Note that it won't show up on your rubric, as I updated it directly in my files.
