### ISSUE TITLE
Assignment 4 CS 0401

### ISSUE THREAD

**Issue by zaxway** [laboon/cs0401#130]
Hi Professor Laboon,

Does our program for assignment 4 need to work with all types of text files or is it specific to only our file? In other words, does our program need to only be compatible with the quiz I create or should it be made to be compatible with all other types of quizzes?

Mohit Jain

**Comment by laboon** [comment]
All quizzes of the same format.  In order to test it, the grader will also use their own "test quiz" file.  Your program should be able to work with that one as well.

**Comment by laboon** [comment]
I believe this answers your question, so I am closing the issue.  Please re-open if you have further question.
