### ISSUE TITLE
[1:00, James Hahn] yoram reminder

### ISSUE THREAD

**Issue by kingsman142** [laboon/cs0401#131]
Hey Bill,

In the assignment5.txt file, you noticed that you put "yoram" in there during the Wednesday lecture.  However, you must have forgotten to change it.  This is just a reminder that we have no idea what "yoram" is and maybe you meant something else.  The exact quote of the specific line is: "2. If a line needs to be modified (ex: a vote count or voter status), do so in yoram."

**Comment by laboon** [comment]
Thank you!  It should read "your program" - I entered it using vi instead of emacs and must have issued some sort of weird command.  Please be sure to put "+2 for issue #131" for 2 bonus points on your assignment sheet.

**Comment by laboon** [comment]
(fixed)
