### ISSUE TITLE
Lab14 Line 21

### ISSUE THREAD

**Issue by jenniferbramson** [laboon/cs0401#133]
I think you meant System.out.println("Fib(" + num + ") = " + num); 
instead of System.out.println("Fib(" + num + ") = 1"); 
since there are two base cases (Fib(0) = 0 and Fib(1) = 1) and one is equal to 0, not 1.

**Comment by laboon** [comment]
Yes, this was a typo.  Thank you.

Fixed in commit 7d063fd

You get +2 bonus points on your last assignment for finding this.
