### ISSUE TITLE
[1:00] Gabriel Melo

### ISSUE THREAD

**Issue by gabrieldoviolao** [laboon/cs0401#27]
Wazzup, Mr Laboon? :D

**Comment by laboon** [comment]
Word!

**Comment by laboon** [comment]
I don't have you listed for this class, is it on your schedule?

**Comment by gabrieldoviolao** [comment]
Hey, Professor Laboon!

I'm the Brazilian guy who talked to you about the Unity engine last week,
remember?
I had to drop out of your class because I had to get another course and
there was a conflict with your lab schedule...
Would it be a problem if I just watched your classes, without being
enrolled?

Gabriel Melo

2015-09-15 16:29 GMT-05:00 Bill Laboon notifications@github.com:

**Comment by laboon** [comment]
No problem at all!  See you in class.
