### ISSUE TITLE
[1.00] Mohit Jain

### ISSUE THREAD

**Issue by zaxway** [laboon/cs0401#31]
Can I use Github to make my websites look more legit and better? I think I heard of this from one of my friends, but I am not exactly sure of what he said for all the purposes of Github.

**Comment by zaxway** [comment]
whoops I forgot to put the [1:00]. I put it now. For the place where it says my name, the Java code would be something like:

import java.util.Scanner;

public class github {
     public static void main .... {
          ......
          Scanner console = new Scanner(System.in);
          String a;
          System.out.println("Name:  " + a);
          a = console.nextLine;
          // more code after this
    }
}

// and some parameters and object oriented programming
// probably only 10000 lines of code with HTML, CSS, and some other programming language.

**Comment by EthanWelsh** [comment]
Mohit,

GitHub is a version control system (first and foremost). It's basically used to store your files online (so you can think of it like DropBox), but it also stores all the changes that you make. Therefore, if you ever wanted to go back to a previous version, you can 'rewind' your file back to that time. GitHub is also great for collaborative working (when two or more people are working on the same project).

Besides version control, I suppose you could take a look at (Github Pages)[https://pages.github.com/]. This may not be what you are looking for, but it's pretty need. Basically, it allows you to host your site on GitHub. If you've already got a domain, then you can 'point' the domain to your GitHub page, such that your page still appears at http://yourpage.com, but every time that you 'push' a change to your site's GitHub repository, your site will automatically update. Pretty cool!

How exactly are you looking to improve your site? There are a lot of neat things that you could use to improve your site in different ways. I'd be happy to lend the little experience I have should you have any specific questions.

Thanks,
Ethan

**Comment by laboon** [comment]
I think Ethan answered your question very well, feel free to ask either one of us if you need more info!
