### ISSUE TITLE
[1:00] Jonathan Rosborough

### ISSUE THREAD

**Issue by jsr43** [laboon/cs0401#42]
That grading scale is beat, yo

**Comment by laboon** [comment]
Is "beat" good or bad?  I am old and don't speak the slang nowadays.

**Comment by jsr43** [comment]
Usually comes with a negative connotation.  Generally used to describe something that is physically damaged, it could also mean "empty" or "used". 
NOTE: I am a law-abiding citizen. That said...

I got a little scared when I saw the difficulty of the grading scale, so that was my reaction.

And yes, it is kinda slangy. Sorry :)
