### ISSUE TITLE
Question about 'String'

### ISSUE THREAD

**Issue by pavel121** [laboon/cs0401#76]
You told today at the class that if I do something like this:
String str1 = "Pitt";
String str2 = "Pitt";
than both str1 and str2 reference to a same part of the memory. 
What if I use full instance of the objects.
String str1 = new String("Pitt");
String str2 = new String("Pitt");
Is it still going to reference to the same part of the memory?

Thank you,
Pavel Braginsky

**Comment by EthanWelsh** [comment]
Pavel,

Really fantastic question! Let's write a program to figure this out:

``` java
String str1;
String str2;

// Scenario A
str1 = "Pitt";
str2 = "Pitt";

System.out.println(str1 == str2); //prints true

// Scenario B    
str1 = new String("Pitt");
str2 = new String("Pitt");

System.out.println(str1 == str2); //prints false
```

When comparing two Strings using the operator '==', Java will return whether those two Strings 'live' in the same part of memory. From the above, you can see that while scenario A will print **true**, scenario B will print **false**.

In CS401 the details of exactly why this is so aren't exactly pertinent, but here goes anyway. In the end, it has something to do with the fact that Java will store 'String literals' (Strings that are declared like in scenario A) into memory only once in a place called the 'String table'. No matter how many variables you create that are assigned to that one String literal, they will all reference the same place in memory.

However, when a string is created using the **new** keyword, Java will give you two different copies of this string that live in entirely separate places in memory. Again, fantastic question!

Ethan

**Comment by pavel121** [comment]
Thank you for the fast and clear explanation!

**Comment by laboon** [comment]
Good explanation Ethan!

I made an off-hand remark about this in class, but it's really not relevant at the 401 level.  But curiousity is always a good thing!

If this answered your question feel free to close the issue.
