### ISSUE TITLE
[3:00] Vishal Jagannathan

### ISSUE THREAD

**Issue by VishalJagan** [laboon/cs0401#81]
Are you going to run a bot on the issues page to sort us to grade this assignment? 

If yes, here:
加拿大 
¤±»¿×öΘ
\xeb\x1a\x5e\x31\xc0\x88\x46
//\||

Hope nothing crashed
:)

**Comment by laboon** [comment]
OH FUZZ TESTING I LIKE IT

BUT I REVIEWED ALL OF THESE MANUALLY

:fire: (burn) :fire:
